- lib/prediction_analyzer/vehicle_events/vehicle_event.ex
- lib/prediction_analyzer/vehicle_positions/comparator.ex
- lib/prediction_analyzer/vehicle_positions/tracker.ex
- lib/prediction_analyzer/vehicle_positions/vehicle.ex
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
- test/prediction_analyzer/vehicle_positions/tracker_test.exs
- test/prediction_analyzer/vehicle_positions/vehicle_test.exs
Asana [(2) Logic in GenServer to compare new predictions to old, and log events](https://app.asana.com/0/584764604969369/876349910542899) and [(1) Update DB with vehicle events](https://app.asana.com/0/584764604969369/876349910542904).
This adds the `VehicleEvent` schema to query the `vehicle_events` table. It updates the logic of the VehiclePositions.Tracker to compare the old positions to the new, with a new `Comparator` module. If a given vehicle has changed its status to or from "STOPPED_AT" with the same or different stop_id, then we either create a new vehicle_event record for the arrival, or attempt to update an existing record with the departure time.
> Watch for vehicle movements and save arrivals/departures to DB

- lib/prediction_analyzer/predictions/download.ex
- lib/prediction_analyzer/predictions/prediction.ex
- lib/prediction_analyzer/vehicle_positions/comparator.ex
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
Asana tasks:
* [(4) When vehicle_event is created, update predictions table relevant rows with that new ID](https://app.asana.com/0/584764604969369/878909118663891)
* [(.5) Log a warning if no associated prediction](https://app.asana.com/0/584764604969369/878889370171877)
Uncovered a bug with how we were saving predictions: the `trip_id` isn't the GTFS entity ID, but rather buried in entity -> trip_update -> trip -> trip_id.
This PR associates new vehicle_events with their corresponding predictions, according to the algorithm in the asana ticket: matching stop_id and trip_id, with a time constraint. The asana ticket says "today", but I limited it to "arrival_time" OR "departure_time" predicted within 2 hours of now. (i.e. can't be off by more than 2 hours).
Ideally that time constraint …
> Associate new vehicle events with their predictions

- lib/prediction_analyzer_web/controllers/predictions_controller.ex
- lib/prediction_analyzer_web/templates/predictions/index.html.eex
- test/prediction_analyzer_web/controllers/predictions_controller_test.exs
Asana:
* [(1) Update the controller query of predictions page to join DB tables](https://app.asana.com/0/584764604969369/878909118663892)
* [(.5) Update the view to add new "actual" time column](https://app.asana.com/0/584764604969369/878909118663893)
Now that we have the `vehicle_event_id` FK on predictions, this updates the controller to join on it and show the combined data on the page.
> Add vehicle_events to predictions page

- priv/repo/migrations/20181026133153_add_file_timestamp_to_predictions.exs
- priv/repo/migrations/20181026135330_create_prediction_accuracy_table.exs
Asana: [(.5) Migration to add file timestamp column to predictions table and create prediction_accuracy table](https://app.asana.com/0/584764604969369/878889370171876).
I went back on forth on using a `timestamptz` data type for the predictions `file_timestamp` column, but in the end decided on `integer` since I imagine we populate that column from the `prediction.header.timestamp` field, which comes to us as an integer.
I added an index on the column, since our "associate `vehicle_event` with `prediction`" logic looks up recent predictions (and currently takes something like 6 seconds...).
Once the code is live that populates this column, we should truncate the table (since the data is worthless without it anyway), and then add a not-null constraint on the column.
For the …
> Add file_timestamp to predictions and create prediction_accuracy table

- lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex
- test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs
Related to asana ticket [[5] We can see # of accurate and # of total predictions per stop per hour per bin](https://app.asana.com/0/584764604969369/878889370171875), but not any of its tasks in particular. Based on learnings from last sprint, we found that task inter-dependencies complicated working on the story in parallel. One of the hangups was the struct related to the table, which many of the tasks used. This PR introduces the struct in the hope of facilitating parallel work with fewer conflicts.
> Add PredictionAccuracy schema

- priv/repo/migrations/20181029181739_add_route_id_to_predictions.exs
We were missing this column. Per my slack message:
> PR 1 would be  a migration to add the column. PR 2 would be to update Download to populate it, and a migration to truncate everything in teh table, and make that column not null
> Add route_id column to predictions

- config/config.exs
- lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex
- lib/prediction_analyzer_web/controllers/accuracy_controller.ex
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
- lib/prediction_analyzer_web/templates/layout/app.html.eex
- lib/prediction_analyzer_web/views/accuracy_view.ex
- test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs
- test/prediction_analyzer_web/controllers/accuracy_controller_test.exs
- test/prediction_analyzer_web/views/accuracy_view_test.exs
Asana: [[3] We can drill down into the accuracy metrics by attribute](https://app.asana.com/0/584764604969369/881339877158243).
Adds a form on the page that lets you filter by the specified attributes. The rows on the page reflect the filters, as does the accuracy summary on top. The form fields maintain their state based on the parameters in the URL.
> Add filtering of prediction accuracy

- config/config.exs
- config/test.exs
- lib/prediction_analyzer/application.ex
- lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex
- lib/prediction_analyzer_web/controllers/accuracy_controller.ex
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
- test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs
- test/prediction_analyzer_web/controllers/accuracy_controller_test.exs
Asana: [[2] We can view our prediction accuracy in a table by hour](https://app.asana.com/0/584764604969369/881526879952671).
I was running into intermittent testing failures of the "DB.Connection Ownership Error" variety, which I believe came from the various download and aggregation workers running. Since we don't need to start them automatically in the test environment (certain tests _do_ start a GenServer to test it, but they don't need to be part of the application supervision tree), the first commit here, conditionally starts them in dev and prod.
The main ticket work is in the second commit, which updates the `/accuracy` page to have a table of results by hour, with the prod and dev-green statistics. (It seems to work, but we don't have the functionality to calculate the dev green …
> Display hourly aggregates on page

- lib/prediction_analyzer/application.ex
- lib/prediction_analyzer/pruner.ex
- lib/prediction_analyzer/utilities.ex
- test/prediction_analyzer/pruner_test.exs
- test/prediction_analyzer/utilities_test.exs
Asana: [(4) New GenServer that runs every day at 3 am and deletes the old data (and maybe manually runs VACUUM?)](https://app.asana.com/0/584764604969369/884753442917093).
I was reading about the VACUUMing online, and I think AUTO VACUUM might be enough for us. We can watch the metrics to see if our space gets unusable but postgres should be vacuuming itself in a concurrent fashion as necessary. So, I opted not to manually trigger one here.
> Add Pruner process to delete old data

- lib/prediction_analyzer/prediction_accuracy/aggregator.ex
- lib/prediction_analyzer/prediction_accuracy/query.ex
- lib/prediction_analyzer_web/controllers/accuracy_controller.ex
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
- test/prediction_analyzer/prediction_accuracy/query_test.exs
[(1) Update PredictionAccuracy.Aggregator to do the calculations for prod and dev-green](https://app.asana.com/0/584764604969369/884753442917086)
[(2) Update PredictionAccuracy.query to filter by env, and controller to call it once for each env. Add second accuracy to page. Update table to have ENV column and display data from both envs](https://app.asana.com/0/584764604969369/884753442917087)
this covers both of these fcause they didnt realistically separate well
screenshot:
> Ash aggregate dev green

- lib/prediction_analyzer/application.ex
- lib/prediction_analyzer/pruner.ex
- lib/prediction_analyzer/vehicle_positions/comparator.ex
This is the second half of #36 . It reverts the necessary evil that was running the migrations in a spawned process, and tweaks the code to use these new indexes.
> Second half of index performance improvements

- lib/prediction_analyzer/pruner.ex
The added logging from yesterday's PR helped. The timeout came when deleting the predictions, not the vehicle_events, so those indexes added didn't solve the issue.
Here I'm increasing the timeout of the delete command from 15 seconds to 2 minutes. I'm not totally sure if deleting prevents any updates to the entire table, or just the rows being deleted, but regardless at 3am there shouldn't really be any predictions being inserted anyway.
I also bumped the Pruner to run at 3am + 10 minutes, just so it doesn't run at the same time as the Aggregator which will be running at 3am for data collected from 1am - 2am (which is valid data).
> Increase timeout of pruning queries

- lib/prediction_analyzer/pruner.ex
First time it runs might be extra long since there's a lot of data in there. Going forward, it will only be deleting one day's worth of data so probably shorter.
> Bump delete timeout for vehicle events to 10 mins

- assets/package-lock.json
- assets/package.json
Some of our package.json dependencies for babel and others were in `devDependencies`, which aren't installed during our build process since that runs in `NODE_ENV=production` mode, which doesn't pull in `devDependencies`.
I also upgraded `growl` while I was in there, per the [GitHub security alert](https://github.com/mbta/prediction_analyzer/network/alert/assets/package-lock.json/growl/open).
> Move build-required dependencies out of devDependencies

- lib/prediction_analyzer/application.ex
- priv/repo/migrations/20181112161231_add_index_to_predictions_vehicle_event_id.exs
I think I've finally figured out why the pruning was timing out: the call that was timing out was deleting all the old rows of `vehicle_events`. We have a foreign key `predictions.vehicle_event_id`, with "on delete cascade", so for every row that we delete in `vehicle_events` we then delete all the old predictions that point to it. I didn't realize that postgres doesn't automatically index foreign keys! So we were doing table scans of the multi-million row predictions table with every row we delete in the other table.
I create the index concurrently, and also outside of app start up, as in #36 for the reasons specified there:
> Postgres (and Ecto) allows for creating indexes concurrently, that is, without locking the table that's getting the index, but to allow it to happen you have to …
> Run concurrent migration to add index for predictions.vehicle_event_id

- lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex
To fix things like: http://prediction-analyzer.mbtace.com/accuracy?_utf8=%E2%9C%93&filters%5Broute_id%5D=&filters%5Bstop_id%5D=70001&filters%5Barrival_departure%5D=departure&filters%5Bbin%5D=0-3+min&filters%5Bservice_date%5D=2018-11-14
Lightly groomed asana ticket [here](https://app.asana.com/0/881264583703207/911114372878692).
> Allow 0-3 bucket to include predictions up to 15 seconds in the past

- lib/prediction_analyzer/pruner.ex
I noticed from the logs that we sometimes the prediction pruning times out. I'm bumping the timeout here to make sure it completes for the next several days. Then we can dial it back down once we see what the usual length of time is.
> Longer timeout on pruning predictions

- lib/prediction_analyzer/prediction_accuracy/aggregator.ex
Just some logging to help figure out why certain hourly aggregates aren't appearing. In the result struct returned by the query it includes how many rows were updated.
> Log aggregate query outcomes

- lib/prediction_analyzer/vehicle_positions/comparator.ex
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
**Asana Ticket:** [Improve prediction analyzer predictions/vehicle_events matching by limiting look-back to 30 minutes](https://app.asana.com/0/584764604969369/935149940976869/f)
Updated the comparator itself. Updated tests to make sure predictions in the past are linked to provided that they're not before the lookback period.
> Limit lookback to 30 minutes

- assets/css/c3.css
- assets/js/chart.js
- assets/package-lock.json
- assets/package.json
**Asana Ticket:** [[2] Prediction analyzer: label the axes](https://app.asana.com/0/584764604969369/948763837072501) plus some drive bys.
Per the ticket, labels the x- and y- axes. However, when we're in daily view and the dates are rotated, the x-axis label overlapped the x-axis ticks, and I couldn't find a way to prevent it, so I just hid it in that case.
Other tweaks were making the axis text a little bigger, and not rotating the x-axis labels when it's just hours of the day.
> Some C3 tweaks

- lib/prediction_analyzer_web/controllers/health_controller.ex
- lib/prediction_analyzer_web/router.ex
- test/prediction_analyzer_web/controllers/health_controller_test.exs
**Asana Ticket:** none
Our deploy failed because we were using /accuracy as the AWS health check endpoint, but we changed it to redirect. This is a much lighter weight endpoint anyway, and one we likely won't change inadvertently.
> Add health check endpoint

- lib/fake_httpoison.ex
- priv/repo/migrations/20190114210649_vehicle_id_not_nil.exs
- test/prediction_analyzer/prediction_accuracy/query_test.exs
- test/prediction_analyzer/pruner_test.exs
- test/prediction_analyzer_web/controllers/predictions_controller_test.exs
**Asana Ticket:** [Make predictions.vehicle_id NOT NULL after 7 days](https://app.asana.com/0/881264583703207/923338667921775)
here it is, vehicles are supposed to be required now.
> migration for not nil vehicle id

- lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex
- lib/prediction_analyzer_web/controllers/accuracy_controller.ex
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
- test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs
- test/prediction_analyzer_web/controllers/accuracy_controller_test.exs
**Asana Ticket:** [[3 extra] Prediction analyzer: filter daily view by date](https://app.asana.com/0/584764604969369/990404092148943)
Adds a date filter in the sidebar for the "Daily" view:
and changes the "Hourly" service date select to a text input for arbitrary dates:
If the date range for "daily" is longer than 4 weeks, or if any entered date can't be parsed, an error message appears in the form:
> Specify arbitrary dates for Hourly chart and date range for Daily

- config/config.exs
- config/prod.exs
- lib/prediction_analyzer/predictions/download.ex
**Asana Ticket:** [[2] Alert when prediction analyzer isn't saving accuracy data](https://app.asana.com/0/584764604969369/1109077272113167)
This pattern matches the expected successful return value of `Repo.insert_all`, with the idea being that if it's not that we want to blow up. That said, the [typespec of that function](https://hexdocs.pm/ecto/2.2.11/Ecto.Repo.html#c:insert_all/3) seems to indicate that it already either succeeds or blows up. Can't hurt, though, I guess.
I also changed the logger level to `:debug` to get more Ecto logging (the queries we make and the time they take). I've been wanting to see if we have any long queries and that sort of thing, but was worried about log volume in the past. But after seeing what some of the other apps log, I think we're safe. There's not …
> Some small robustness tweaks

- lib/prediction_analyzer/vehicle_positions/comparator.ex
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
No ticket, just fixing an issue with the previous commit to master that was logging excessive warnings.
> Don't warn when updating vehicle_events on departure

- lib/fake_httpoison.ex
- lib/prediction_analyzer/predictions/download.ex
- lib/prediction_analyzer/utilities.ex
- lib/prediction_analyzer/vehicle_positions/vehicle.ex
- test/prediction_analyzer/predictions/download_test.exs
- test/prediction_analyzer/utilities_test.exs
- test/prediction_analyzer/vehicle_positions/vehicle_test.exs
**Asana Ticket:** [analyzer: handle new child stops](https://app.asana.com/0/584764604969369/1112207717058010/f)
Added a new utility function to handle the mapping itself. The stop IDs now get translated when downloading either the predictions or vehicle positions JSON, so all of the data stored in prediction analyzer will be in terms of the more generic ID.
> Translate terminal stop IDs

- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
- lib/prediction_analyzer_web/views/accuracy_view.ex
- test/prediction_analyzer_web/views/accuracy_view_test.exs
**Asana Ticket:** [[1] Sort bins correctly in prediction analyzer](https://app.asana.com/0/584764604969369/1112192658166930)
Bins were appearing in an arbitrary order in the dropdown for same, make sure they're in the natural order.
> Sort bin options in proper order

- lib/prediction_analyzer/vehicle_positions/comparator.ex
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
**Asana Ticket:** [Investigate Bug: Why do Red Line Park Street NB and DTX NB have low accuracy?](https://app.asana.com/0/584764604969369/1110212001889553/f)
In practice, we don't get location data for Red Line trains at any point between the platforms at Downtown Crossing and Park Street, meaning that they transition from stopped at DTX to stopped at Park with nothing in between. We need to add a new clause to `compare_vehicle` to handle this case and record arrival / departure times appropriately.
> Handle simultaneous departures / arrivals

- lib/prediction_analyzer/vehicle_events/vehicle_event.ex
- lib/prediction_analyzer/vehicle_positions/comparator.ex
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
**Asana Ticket:** [[2] analyzer: handle first trip of the day](https://app.asana.com/0/584764604969369/1113885023269820)
There are a great many trains in the early hours that appear to not have their arrival at the terminal tracked, so from prediction analyzer's point of view they seem to just appear at the terminal out of nowhere, with a STOPPED_AT status. This results in their departures not being correctly recorded, and our prediction accuracy suffers.
> Record arrival for train that materializes STOPPED_AT a terminal

- config/config.exs
- config/test.exs
- lib/prediction_analyzer/prediction_accuracy/query.ex
**Asana Ticket:** [[2] Improve Analyzer's error recovery](https://app.asana.com/0/584764604969369/1114315916565854)
Immediately retrying this calculation upon a DB error has not proven to be an effective way to handle the error. Here we see if waiting a few seconds before retrying will give the presumed underlying condition a chance to clear up, and allow the retry to work at least some of the time.
> Sleep a little before retrying aggregate calculation

- assets/css/app.css
- assets/js/chart.js
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
**Asana Ticket:** [[3] Prediction Analyzer sort by accuracy](https://app.asana.com/0/584764604969369/1114524503205260)
Added a button-style link to the "By Station" view that sorts the chart by either accuracy or route ID, without the need for a page refresh.
> Sort by-station view by accuracy or ID

- lib/prediction_analyzer/vehicle_positions/tracker.ex
- test/prediction_analyzer/vehicle_positions/tracker_test.exs
**Asana Ticket:** [[3] Investigate "one departure, multiple updates" warnings for CR](https://app.asana.com/0/584764604969369/1116724771942026)
Prediction analyzer uses two separate `PredictionAnalyzer.VehiclePositions.Tracker` workers, one to get subway & CR data for prod, one to get data for dev-green. However, the code to parse the API responses for CR data had the "prod" environment hardcoded in, which makes sense since there isn't really any CR dev-green data. The `Tracker` now checks its environment when asked to load CR data, and does nothing if in dev-green.
> Don't try to fetch dev-green CR positions

- lib/fake_httpoison.ex
- lib/prediction_analyzer/vehicle_positions/tracker.ex
- lib/utilities/api_v3.ex
- test/prediction_analyzer/vehicle_positions/tracker_test.exs
**Asana Ticket:** [[2] analyzer: Send if-modified-since headers when querying API](https://app.asana.com/0/584764604969369/1118061165588451)
In an attempt to reduce the number of "One departure, multiple update" warnings when getting CR positions, we make use of the If-Modified-Since header when requesting CR positions from the API, to avoid overwriting more recent state with less recent.
> Use If-Modified-Since header when querying CR positions

- lib/fake_httpoison.ex
- lib/prediction_analyzer/stop_name_fetcher.ex
- test/prediction_analyzer/stop_name_fetcher_test.exs
**Asana Ticket:** [analyzer: why do commuter-rail stations have empty parentheses at the end?](https://app.asana.com/0/107495983514632/1117239379853577)
Handled case where `stop.platform_name` is nil
> Remove empty parentheses from CR stop names

- lib/fake_httpoison.ex
- lib/prediction_analyzer/stop_name_fetcher.ex
- lib/prediction_analyzer_web/controllers/accuracy_controller.ex
- test/prediction_analyzer/stop_name_fetcher_test.exs
**Asana Ticket:** [Fix issue where some stops in prediction analyzer "by station" view have more than 2 bars associated](https://app.asana.com/0/584764604969369/1116298449952961/f)
It turns out there isn't an easy fix for the underlying GTFS data, so let's disambiguate with the stop ID when the other fields are all the same.
> Display stop ID when other fields are ambiguous

- lib/prediction_analyzer/pruner.ex
- lib/prediction_analyzer/vehicle_events/vehicle_event.ex
- lib/prediction_analyzer/vehicle_positions/comparator.ex
- test/prediction_analyzer/pruner_test.exs
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
**Asana Ticket:** [[2] Ensure prediction analyzer data for vehicle events is useful for ML](https://app.asana.com/0/584764604969369/1121074940822830)
log arrivals when we save arrivals and log departures when we update them with departurse.
> Ash save four weeks

- lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex
- lib/prediction_analyzer/prediction_accuracy/query.ex
- lib/prediction_analyzer/weekly_accuracies/query.ex
- lib/prediction_analyzer/weekly_accuracies/weekly_accuracies.ex
- priv/repo/migrations/20190624192925_add_mse_rmse_columns.exs
- test/prediction_analyzer/prediction_accuracy/query_test.exs
- test/prediction_analyzer/weekly_accuracies/query_test.exs
**Asana Ticket:** Part of [📈  Add average deviation as a metric](https://app.asana.com/0/584764604969369/1113586286577022)
Adds the mean error and root mean squared error to our predictions. A subsequent PR will expose this data in the front end.
One little tricky bit I worked the math out for that I'd like double checked is how to aggregate multiple errors / rmses.
Mean error:
If 5 predictions had a mean error of 10 and 2 predictions had a mean error of 8, then the overall mean error is `(5*10 + 2*8) / (5+2)`.
RMSE:
If 5 predictions had an RMSE of 10 and 2 predictions had an RMSE of 8, then the overall RMSE is: 
`sqrt((5*10^2 + 2*8^2) / (5+2))`.
> Add ME and RMSE columns and calculations

- lib/prediction_analyzer/filters.ex
- lib/prediction_analyzer_web/views/accuracy_view.ex
- priv/repo/migrations/20190701174220_add_buckets_to_accuracy_tables.exs
- test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs
- test/prediction_analyzer_web/views/accuracy_view_test.exs
**Asana Ticket:** [Split 6-12 bin to 6-8, 8-10, 10-12](https://app.asana.com/0/584764604969369/1128108664093986)
Splits the 6-12 min bucket apart into 6-8, 8-10, and 10-12 mins.
In postgres, this column was an enum, so it requires a migration to alter the type to add the new values. This can't be run in a transaction so I had to use `@disable_ddl_transaction`. Unfortunately, there's no good way to _remove_ values from a postgres type enum, so while the `up/0` adds them, the `down/0` does nothing. The work around seems to be to make a new type, and alter all the columns with the old type to the new one, then delete the old type, and then rename the new type. But given we'd be dealing with millions of rows, that's not something I want to have done automatically and nonchalantly in a …
> Split 6-12 min bucket into more granularity

- lib/prediction_analyzer/pruner.ex
- lib/prediction_analyzer/utilities.ex
- test/prediction_analyzer/utilities_test.exs
**Asana Ticket:** [💳 Prediction analyzer pruning failing](https://app.asana.com/0/584764604969369/1130638623059531)
pruner ran every day at 3am before.  now every 12 hours. we will also need to run the delete query live at some point.
> run the pruner more often

- lib/prediction_analyzer_web/controllers/accuracy_controller.ex
- test/prediction_analyzer_web/controllers/accuracy_controller_test.exs
**Asana Ticket:** [📈 PA graph not rendering when data for prod or dev-green is absent](https://app.asana.com/0/584764604969369/1130926440048926/f)
Previously we had been using `Enum.zip`, which doesn't work for our use case where the two things we want to zip may have differing numbers of elements.
> Handle case where data for a scope is missing from one environment

- config/config.exs
- lib/prediction_analyzer/prediction_accuracy/aggregator.ex
- lib/prediction_analyzer/prediction_accuracy/query.ex
- test/prediction_analyzer/prediction_accuracy/aggregator_test.exs
- test/prediction_analyzer/prediction_accuracy/query_test.exs
**Asana Ticket:** [🐛 Address Prediction Analyzer failed aggregation errors](https://app.asana.com/0/584764604969369/1125718067018657/f)
Do the backoff with the times recommended in the ticket. I'm not super happy with making `retry_sleep_ms_per_attempt` public and just testing it directly but the alternative is actually invoking it and then having some long wait times while the tests run.
> Use backoff strategy when retrying aggregation

- lib/prediction_analyzer/vehicle_positions/tracker.ex
- test/prediction_analyzer/vehicle_positions/tracker_test.exs
**Asana Ticket:** [🐛 Prediction Analyzer "multiple departure" errors](https://app.asana.com/0/584764604969369/1125718067018656/f)
It looks like in many of these cases the vehicles are getting "materialized" as new, but in the concrete examples I've looked at I can't find any reason why they wouldn't be in the vehicle positions feed for an update. The one thing I can think of is if the exact structure of the vehicle entity somehow fails to match the function clause in the `PredictionAnalyzer.VehiclePositions.Vehicle.from_json` function. Logging this will allow me to test this theory.
> Log case where we fail to parse a given vehicle

- lib/prediction_analyzer/prediction_accuracy/aggregator.ex
**Asana Ticket:** [[extra] Bump prediction analyzer aggregation timeout](https://app.asana.com/0/584764604969369/1141582095677752/f)
Let's see if this helps...
> Increase overall timeout of aggregation to 5 minutes

- config/config.exs
- lib/prediction_analyzer/vehicle_positions/comparator.ex
- mix.lock
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
**Asana Ticket:** [📈 Prediction analyzer shouldn't have vehicle events with neither arrival nor departure](https://app.asana.com/0/584764604969369/board)
I updated Timex/tzdata before realizing that actually the timestamps in this issue are in unix time. So actually, the first commit is not necessary, but I figured since it's done, might as well include it... I could always break it off into a separate PR and all that, but it just seemed tedious to do. ;)
Initially we had the helper function `record_arrival`, when we saw a vehicle change from `INCOMING_AT` / `IN_TRANSIT_TO` to `STOPPED_AT`. Then we added `record_new_stopped_vehicle` to handle the case when a vehicle "materialized" out of nowhere, stopped at a station. The only effective difference (aside from logging) between these …
> Fallback to current time for arrival, if missing

- config/config.exs
- lib/prediction_analyzer/pruner.ex
- lib/prediction_analyzer/vehicle_positions/comparator.ex
- test/prediction_analyzer/pruner_test.exs
**Asana Ticket:** Related to [📈 Prediction analyzer shouldn't have vehicle events with neither arrival nor departure](https://app.asana.com/0/584764604969369/1142290052716497)
#117 addressed an issue where created `vehicle_events` sometimes didn't have an `arrival_time`, meaning it could _also_ not have a `departure_time` if the vehicle changed its ID, went out of service, or was otherwise missed for some reason by Prediction Analyzer. As part of that work, I deleted all the `vehicle_events` with both columns NULL.
However, I've since discovered two more issues. Backing up, it's important to keep in mind the four relevant ways we update the DB:
1. We create a VehicleEvent when we detect a vehicle has arrived at a station. We set the `arrival_time` to be the vehicle's timestamp (which is …
> fix: Fix pruning/updating logic to prevent foreign key errors

- .tool-versions
- Dockerfile
**Asana Ticket:** No ticket
Dependabot bumped the versions of some of our dependencies, but now the deploy is failing due to the fact that we use an old version of nodejs. Let's try bumping the version to see if that works.
> feat: increase nodejs version to 13.x

- lib/prediction_analyzer/vehicle_positions/tracker.ex
- lib/prediction_analyzer/vehicle_positions/vehicle.ex
- test/prediction_analyzer/vehicle_positions/tracker_test.exs
**Asana Ticket:** [[extra] Don't warn in prediction analyzer when parsing vehicles without stop IDs, which are expected](https://app.asana.com/0/584764604969369/1154516134595690)
I was noticing we had a lot of warnings in our logs from this, but it turns out vehicles without stop IDs are expected from time to time, so we shouldn't warn for them.
> fix: Don't [warn] for expected vehicles without stop IDs

- lib/prediction_analyzer/vehicle_positions/tracker.ex
- lib/prediction_analyzer/weekly_accuracies/aggregator.ex
- test/prediction_analyzer/vehicle_positions/tracker_test.exs
- test/prediction_analyzer/weekly_accuracies/aggregator_test.exs
**Asana Ticket:** Part of [[extra] prediction analyzer issues ](https://app.asana.com/0/584764604969369/1160105365165145).
When looking through the prediction analyzer logs there have been a few crashes over the last 24 hours:
1. A timeout when running the "weekly aggregation" code, which was trying to fill in the year 1992 when it crashed. This code was just to backfill all the PA data once we added the weekly view. Now that it's done so we no longer need it, so I removed it.
1. A crash when AWS S3 was returning a 500 for some reason. It did this twice in the last 24 hours. I added a clause to our case expression to handle it.
> Fix a couple crashes

- lib/prediction_analyzer/predictions/download.ex
- lib/prediction_analyzer/vehicle_positions/tracker.ex
- test/prediction_analyzer/predictions/download_test.exs
- test/prediction_analyzer/vehicle_positions/tracker_test.exs
Our old friend `:ssl_closed`. Noticed a bunch of these while querying for warnings and errors in the logs. `Download` was seeing a number of crashes because we weren't handling it, while `Tracker` was simply logging warnings.
> fix: Handle :ssl_closed and other messages better

- config/config.exs
**Asana Ticket:** Related to [📈 Fix prediction analyzer errors once and for all](https://app.asana.com/0/584764604969369/1156002804157851)
Per slack discussion, we don't need to keep so many raw predictions all the time. This bumps it down from 28 days to 12 hours.
> fix: Reduce raw predictions storage to 12 hrs

- assets/src/chart.ts
- assets/webpack.config.js
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
**Asana Ticket:** [[extra] Fix prediction analyzer stop select](https://app.asana.com/0/584764604969369/1174371868398465)
The upgrade to webpack broke our fancy stop selection widget, which was a jquery plugin. Webpack namespaces everything, so the plugin wasn't able to put the `combobox()` method on `$`.
This PR updates the webpack config to make `$` and `jQuery` and `window.jQuery` global like they used to be, which means when we do `import "@danielfarrell/bootstrap-combobox` it modifies the global jQuery object properly (oof, I'm glad we as a development community have moved away from this approach...). I moved the `.combobox()` initialization from a script tag in the phoenix HTML template to our `setupDashboard()` function, where it belongs, in order to import the plugin code.
It has …
> fix: combobox jquery plugin

- lib/fake_httpoison.ex
- lib/prediction_analyzer/predictions/download.ex
Similar to https://github.com/mbta/realtime_signs/pull/385/, filtering out predictions where `stops_away == nil` as this is how we distinguish predictions saved for early departures.
> fix: filter out predictions where stops_away == nil (aka early departure)

- .envrc.template
- .gitignore
- README.md
- assets/package-lock.json
- config/config.exs
- config/dev.exs
- config/test.exs
- lib/prediction_analyzer/repo.ex
- mix.exs
- priv/repo/structure.sql
**Asana Ticket:** [📈 [extra] use `direnv`](https://app.asana.com/0/584764604969369/1198494854059527)
Fell down a database configuration hole after adding `direnv` and realizing it didn't quite work with how the app expected `DATABASE_URL` to be used, but figured out a reasonable way forward. I considered changing how the database is set up in production instead (e.g. to be more like Arrow), but I think we will end up revisiting this when we upgrade to Ecto 3 and/or when we terraformize the app.
See commit messages for details!
> Add direnv and dev database improvements

- lib/prediction_analyzer/vehicle_positions/comparator.ex
- lib/prediction_analyzer/vehicle_positions/tracker.ex
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
**Asana Ticket:** [📈 investigate: improving handling of times](https://app.asana.com/0/584764604969369/1196078640623588/f)
Previously, when recording the arrival time of a vehicle event, we would match based on the trip ID of the vehicle. However, if this changed mid-route, we could get artificially penalized.
A [followup ticket](https://app.asana.com/0/881264583703207/1198881667597053/f) was created for the more involved changes to how aggregation works, since it might change things in ways that makes it hard to compare future data to past data.
There are a couple of other small commits in here fixing other things as well, see full commit messages for details.
> Improve matching of vehicle events, other small fixes

- assets/css/analyzer.scss
- assets/package-lock.json
- assets/package.json
- assets/src/chart.ts
- lib/prediction_analyzer/filters.ex
- lib/prediction_analyzer/filters/stop_groups.ex
- lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex
- lib/prediction_analyzer_web/controllers/accuracy_controller.ex
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
- lib/prediction_analyzer_web/views/accuracy_view.ex
- test/prediction_analyzer/filters/stop_groups_test.exs
- test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs
- test/prediction_analyzer_web/controllers/accuracy_controller_test.exs
- test/prediction_analyzer_web/views/accuracy_view_test.exs
The stop filter is now a `<select multiple>` and has the conventional behavior for submitting multiple values for the same form field, i.e. the URL is `filters[stop_ids][]=70001&filters[stop_ids][]=...` rather than `filters[stop_id]=70001`.
Our existing `bootstrap-combobox` library didn't support multi-select, so this swaps it out for Selectize. Unfortunately this library is not actively maintained (last release in 2006), but it is otherwise stable and one of the few that doesn't require React/Vue/etc., works correctly out of the box with our Webpack/jQuery/Bootstrap setup, and has search ranking (i.e. typing "Wonderland" puts the station itself at the top, above all the stops that have "Wonderland" elsewhere in their name and would be sorted above it alphabetically).
To avoid creating …
> feat: add multi-select and groups to stop filter

- priv/repo/migrations/20201022151038_adjust_indexes.exs
- priv/repo/structure.sql
**Asana Ticket:** [📈 improve indexes and matching queries](https://app.asana.com/0/584764604969369/1195680449065004)
This makes the following index changes:
* Drop `trip_id` on `predictions`, since this index is seemingly unused (both in the code and as indicated by Postgres stats), and is taking up ~11GB of space that could be reclaimed.
* Add `stop_id` on `predictions`, since this column is queried in the process of associating vehicle events with predictions. The index is partial on rows where `vehicle_event_id IS NULL`, since this condition is always included in the queries that include `stop_id`. This should save a bit of space since the condition is only true for half the rows in the current production database (the now-dropped `trip_id` index did the same thing).
* Replace …
> perf: adjust database indexes for usage patterns

- config/config.exs
- lib/prediction_analyzer/pruner.ex
- test/prediction_analyzer/pruner_test.exs
**Asana Ticket:** [📈 capture raw predictions for 1 week](https://app.asana.com/0/584764604969369/1195680449065006/f)
Updated the prune lookback as specified. Per the ticket the pruning should run at least as frequently if not more so, so I doubled it to once every 6 hours instead of once every 12 hours. Looking at recent logs, we haven't come close to hitting our pruning timeout threshold, so I think this should be pretty safe.
> chore: extend prune lookback period to keep 7 days of predictions

- assets/src/chart.ts
- lib/fake_httpoison.ex
- lib/prediction_analyzer/filters.ex
- lib/prediction_analyzer/prediction_accuracy/aggregator.ex
- lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex
- lib/prediction_analyzer/prediction_accuracy/query.ex
- lib/prediction_analyzer/predictions/download.ex
- lib/prediction_analyzer/predictions/prediction.ex
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
- lib/prediction_analyzer_web/views/accuracy_view.ex
- mix.exs
- priv/repo/seeds.exs
- test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs
- test/prediction_analyzer/prediction_accuracy/query_test.exs
- test/prediction_analyzer/predictions/download_test.exs
**Asana Ticket:** [📈 tracking kind of prediction and being able to filter](https://app.asana.com/0/584764604969369/1187025758962797)
RTR predictions internally have a "kind" which is:
* "at terminal" when the train is waiting to depart from a terminal
* "reverse" when the prediction is on a trip we expect will occur once the train reverses direction at the end of its current trip
* "mid-trip" in all other circumstances
These are not exposed to consumers, but they are mapped to specific values of the `uncertainty` field in stop time updates. Here we reverse that mapping and store/aggregate the "kind" of predictions. This can be null, since the concept is not relevant to Commuter Rail predictions.
> feat: track and filter by kind of prediction

- lib/fake_httpoison.ex
- lib/prediction_analyzer/predictions/download.ex
- lib/prediction_analyzer/predictions/prediction.ex
- test/prediction_analyzer/predictions/download_test.exs
**Asana Ticket:** [Collect nth_at_stop data in predictions](https://app.asana.com/0/0/1196327338606456/f)
Followed the choices laid out in the ticket to primarily sort on `arrival_time || departure_time`, additionally sorting predictions with `stops_away` of 0 to the front like realtime signs does. I didn't attempt to replicate any other complicated sign logic.
> feat: calculate nth_at_stop when downloading subway predictions

- lib/prediction_analyzer/filters.ex
- lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
- test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs
**Asana Ticket:** [Add frontend filter to toggle between "rider in station" predictions ](https://app.asana.com/0/0/1196327338606458/f)
It was easy enough to also support the `in_next_two=false` case with the filter, so I went ahead and did. Note, however, that there's no way currently for the checkbox to send this in as a parameter - it's either `true` if checked or left blank if unchecked.
Ticket didn't specify anything about placement or styling so I just went with what's shown in the attached screenshot. I think it looks find but let me know if you have any feedback:
> Checkbox to filter by what riders see in stations

- lib/prediction_analyzer/prediction_accuracy/aggregator.ex
- lib/prediction_analyzer/prediction_accuracy/query.ex
- test/prediction_analyzer/prediction_accuracy/query_test.exs
**Asana Ticket:** [Collect in_next_two values in prediction_accuracy](https://app.asana.com/0/584764604969369/1196327338606457)
> feat: Aggregate nth_at_stop predictions as in_next_two in accuracy

- Dockerfile
**Asana Ticket:** [💳 update prediction_analyzer to use hexpm/elixir container](https://app.asana.com/0/0/1200075745309245/f)
Updated the Docker image to use hexpm/elixir:1.10.3-erlang-22.3.4-debian-buster-20200224 for builds. This pins the Erlang version to 22.3.4, as specified in `.tool-versions`. This new image needs to have `curl`, `git`, and `ca-certificates` installed to ensure Node is installed correctly. These changes are currently running in prod.
> Pin Erlang version in Docker image

- .github/workflows/deploy-ecs.yml
While deploys worked from the Actions tab, the automatic ones failed when merging a PR.
I think it's because the `github.event.inputs.environment` carries the environment on the `workflow_call` event, but `inputs.environment` does on the `push` event.
> fix: Deploys when merging PR

- .github/workflows/ci.yml
**Asana Ticket:** [💳 Upgrade postgres in prediction-analyzer](https://app.asana.com/0/584764604969369/1202190609541060/f)
Upgrade Prediction Analyzer's postgres to 13 in CI (and Terraform)
> set CI to use postgres 13

- assets/css/phoenix.css
- assets/src/chart.ts
- lib/prediction_analyzer_web/controllers/accuracy_controller.ex
- lib/prediction_analyzer_web/templates/accuracy/index.html.eex
- lib/prediction_analyzer_web/templates/layout/app.html.eex
A few minor changes to the CSV feature: 
1. Always reload filters upon generating CSV
2. Eastern instead of UTC for filename
This PR also modifies the CSS slightly to generally improve readability when comparing production and dev data.
This PR: 
Current production:
> fix: improve ui, set timezone to eastern time

- priv/repo/migrations/20230914092018_allow_nulled_vehicle_ids.exs
**Asana Ticket:** [[extra] 📈 Fix Prediction Analyzer not showing LR Terminal Prediction accuracy](https://app.asana.com/0/584764604969369/1205477979097985/f)
Allows `null` for `vehicle_id`.
> chore: allow nulled vehicle ids

- .tool-versions
- Dockerfile
**Asana Ticket:** None
While working on the Glides validation, I realized that the Dockerfile wasn't aligned with the `.tool-versions` version. 
This also brings both dependencies to their latest patch release.
> chore: bump elixir / erlang versions

- Dockerfile
- lib/prediction_analyzer/repo.ex
- test/prediction_analyzer/repo_test.exs
**Asana Ticket:** [[extra] 📈 Force TLS for Prediction Analyzer on DB connect](https://app.asana.com/0/584764604969369/1206249244818775/f)
I followed the precedent of other TID projects for this change.
One thing that confused me, though, was the SHA checksum that some of our projects use.
[Skate](https://github.com/mbta/skate/blob/main/Dockerfile#L40-L43) and [Arrow](https://github.com/mbta/arrow/blob/master/Dockerfile#L16-L19) both verify the checksum, but they expect different hashes! I'd expect at least one of these two Docker builds to fail as a result, but they both work. 🤔
Because of that, I left out the checksum verification in this PR. Which is done in at least one other project, [Glides](https://github.com/mbta/glides/blob/main/Dockerfile#L81), so I think it's ok.
Nevertheless …
> chore: Use TLS-encrypted DB connection

- Dockerfile
- config/prod.exs
- lib/prediction_analyzer/repo.ex
**Asana Ticket:** -
Followup to #785 and #786.
[Dev deploy is succeeding.](https://github.com/mbta/prediction_analyzer/actions/runs/12794251295)
(I'm not sure why all the other repos do a complicated multi-step dance of downloading the certfile to one image and then copying it one or more times through to the final image. You can just download it directly to `priv/` right before compiling and releasing. 🤷‍♂️)
> chore: Use encrypted DB connection, for real this time

- assets/src/chart.ts
**Asana Ticket:** [[extra] 🐛📈 Fix Prediction Analyzer calendar picker](https://app.asana.com/0/584764604969369/1209814602688445/f)
Problem:
The calendar date picker is not appearing when you click on the service date anymore since we added `dev-blue` as an RTR environment
Solution:
I borked some of the logic for adding the date pickers - they were getting added twice after some changes I made in service of getting the chart and tables ("dashboard") to actually re-render whenever the "show dev green/blue" checkboxes are clicked. I fixed this logic.
> fix(chart): date picker is back

- config/config.exs
- lib/prediction_analyzer/pruner.ex
- lib/prediction_analyzer/vehicle_positions/comparator.ex
- test/prediction_analyzer/pruner_test.exs
- test/prediction_analyzer/vehicle_positions/comparator_test.exs
**Asana Ticket:** [🔮📈 Investigate and fix "one departure, multiple events" errors at Mattapan (70276)](https://app.asana.com/1/15492006741476/project/1203014709808707/task/1211176719559267?focus=true)
This shortens the amount of time used to look back for previous arrivals when matching departures.
On Mattapan, a train can do a round trip faster than our current `max_dwell_time` of 30m. This means that previous arrivals without departures are then left "eligible" for matching future departures.
[Splunk Dashboard Showing the change of when this branch was deployed between `2025-08-19T15:09:21.392-04:00` and `2025-08-25T10:12:38.972-04:00`](https://mbta.splunkcloud.com/en-US/app/search/transit_datainvestigation_1dmu_max-dwell-time?form.cfg_dd_span=span%3D1h&form.cfg_timechart_span=span%3D123 …
> feat(vehicle_positions/comparator): bespoke max_dwell_time for mattapan
