config/test.exs, lib/prediction_analyzer_web/controllers/predictions_controller.ex, lib/prediction_analyzer_web/router.ex, lib/prediction_analyzer_web/templates/predictions/index.html.eex, lib/prediction_analyzer_web/views/predictions_view.ex, test/prediction_analyzer_web/controllers/predictions_controller_test.exs, test/test_helper.exs
[[3] A user can see recent predictions](https://app.asana.com/0/584764604969369/872531721286022)
this encompasses all the subtasks sorry gabe :/
=> make an html table to look at the next 100 predictions by arrival time

priv/repo/migrations/20181022210113_add_vehicle_events_table.exs
Asana: [(.5) Migration to add vehicle_events table](https://app.asana.com/0/584764604969369/876349910542897)
Table to record when a vehicle arrives at / departs from a stop.
=> Migration for new vehicle events table

priv/repo/migrations/20181025152446_add_vehicle_event_id_to_predictions.exs
[(.5) Migration to add vehicle_event_id to predictions table](https://app.asana.com/0/584764604969369/878909118663894)
add vehicle_event_id to predictions.
=> migration for vehicle_event_id

lib/prediction_analyzer_web/controllers/accuracy_controller.ex, lib/prediction_analyzer_web/router.ex, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex, test/prediction_analyzer_web/controllers/accuracy_controller_test.exs
[(.5) Route to /accuracy page](https://app.asana.com/0/584764604969369/878909118663899)
[(.5) Controller to return recent accuracies](https://app.asana.com/0/584764604969369/878909118663900)
[(.5) View/Template HTML table of results](https://app.asana.com/0/584764604969369/878909118663901)
=> add page for listing accuracies

lib/prediction_analyzer/predictions/download.ex, lib/prediction_analyzer/predictions/prediction.ex, lib/prediction_analyzer_web/templates/predictions/index.html.eex, priv/repo/migrations/20181029192143_require_route_id.exs, test/prediction_analyzer/vehicle_positions/comparator_test.exs, test/prediction_analyzer_web/controllers/predictions_controller_test.exs
[gabe comment](https://mbtace.slack.com/archives/G7MT9F2TS/p1540833590019100)
=> use the route_id column.  its important

priv/repo/migrations/20181029203022_add_dev_green.exs
[(.5) Migrations](https://app.asana.com/0/584764604969369/884753442917083)
=> add column and type for environment

README.md, config/test.exs, lib/fake_httpoison.ex, lib/prediction_analyzer/application.ex, lib/prediction_analyzer/predictions/download.ex, lib/prediction_analyzer/predictions/prediction.ex, lib/prediction_analyzer_web/templates/predictions/index.html.eex, test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs, test/prediction_analyzer/predictions/download_test.exs, test/prediction_analyzer/vehicle_positions/tracker_test.exs
[(1) Update Predictions.Download to download from prod and dev-green and add to DB](https://app.asana.com/0/584764604969369/884753442917085)
codecov seems to be giving me a 500, but ill add some tests
=> add environment to predictions:

lib/prediction_analyzer/application.ex, lib/prediction_analyzer/vehicle_events/vehicle_event.ex, lib/prediction_analyzer/vehicle_positions/comparator.ex, lib/prediction_analyzer/vehicle_positions/tracker.ex, lib/prediction_analyzer/vehicle_positions/vehicle.ex, lib/prediction_analyzer_web/controllers/vehicle_events_controller.ex, lib/prediction_analyzer_web/templates/vehicle_events/index.html.eex, test/prediction_analyzer/vehicle_positions/comparator_test.exs, test/prediction_analyzer/vehicle_positions/tracker_test.exs, test/prediction_analyzer/vehicle_positions/vehicle_test.exs
[(1) Update VehiclePositions.Tracker to download from mbta-gtfs-s3 and mbta-gtfs-s3-dev-green](https://app.asana.com/0/584764604969369/884753442917084)
=> Ash dev green vehicles

lib/prediction_analyzer/prediction_accuracy/aggregator.ex, lib/prediction_analyzer/predictions/prediction.ex, lib/prediction_analyzer_web/controllers/predictions_controller.ex, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/templates/predictions/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex, test/prediction_analyzer/predictions/prediction_test.exs, test/prediction_analyzer_web/controllers/predictions_controller_test.exs, test/prediction_analyzer_web/views/accuracy_view_test.exs
Asana: [Click on an hour in the prediction analyzer and see the predictions that went into that as a CSV](https://app.asana.com/0/584764604969369/911114372878693)
=> Download CSV of predictions that went into statistics

priv/repo/migrations/20181130203837_add_vehicle_id_to_predictions.exs, priv/repo/migrations/20181203152039_add_index_on_vehicle_id_predictions.exs
[(1) Add predictions.vehicle_id column and index (making app start up migrations async, if necessary).](https://app.asana.com/0/584764604969369/929449096386419)
=> add vehicle id and index to predictions

assets/css/app.css, assets/css/c3.css, assets/js/chart.js, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/templates/layout/app.html.eex
Asana: [[3] Style prediction analyzer somewhat](https://app.asana.com/0/584764604969369/931950192635050).
Mockup is [here](https://projects.invisionapp.com/share/CVOX8S7YK8Q#/screens/329214426).
=> Do some rudimentary styling of the page

lib/prediction_analyzer_web/controllers/predictions_controller.ex, priv/repo/seeds.exs, test/prediction_analyzer_web/controllers/predictions_controller_test.exs
**Asana Ticket:** [On the prediction analyzer make sure 26 o'clock downloads the right CSV](https://app.asana.com/0/584764604969369/950335284985083/f)
We should add 1 instead of subtract 1 from the date.
=> On the prediction analyzer make sure 26 o'clock downloads the right CSV

lib/prediction_analyzer_web/controllers/accuracy_controller.ex, lib/prediction_analyzer_web/views/accuracy_view.ex, test/prediction_analyzer_web/controllers/accuracy_controller_test.exs, test/prediction_analyzer_web/views/accuracy_view_test.exs
**Asana Ticket:** [Prediction Analyzer works when switching to daily in all cases](https://app.asana.com/0/584764604969369/960766001017225/f)
Don't try to generate the download link for daily charts.
=> Prediction Analyzer works when switching to daily in all cases

.github/PULL_REQUEST_TEMPLATE.md
=> Add checkbox to PR template

assets/css/app.css, assets/js/chart.js, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex, test/prediction_analyzer_web/views/accuracy_view_test.exs
**Asana Ticket:** [[3 extra] Prediction analyzer: format date/time selection more in line with design](https://app.asana.com/0/1101545135637620/990404092148944)
Changed the chart-range "Hourly" vs. "Daily" selection UI from a `select` to a set of links, as pictured in https://projects.invisionapp.com/share/CVOX8S7YK8Q#/screens/329214430
=> Change chart range from select to links

assets/js/chart.js, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex, test/prediction_analyzer_web/views/accuracy_view_test.exs
**Asana Ticket:** [clicking on a new route should not reset the form selection](https://app.asana.com/0/584764604969369/1109957966379444/f)
Use the same basic method as was used for the hourly / daily buttons.
=> Clicking on a new route should not reset the form selection

lib/prediction_analyzer/vehicle_positions/comparator.ex, test/prediction_analyzer/vehicle_positions/comparator_test.exs
**Asana Ticket:** [Analyzer: score departures for predictions when the vehicle is already there](https://app.asana.com/0/584764604969369/1112210242551978/f)
Using the approach outlined in the ticket.
=> Also do the association of vehicle events to predictions on departure

lib/prediction_analyzer/prediction_accuracy/aggregator.ex, lib/prediction_analyzer/prediction_accuracy/query.ex, test/prediction_analyzer/prediction_accuracy/query_test.exs
**Asana Ticket:** [Analyzer: Handle occasional database errors](https://app.asana.com/0/584764604969369/1110825829359410/f)
Split out a new `do_calculate_aggregate_accuracy` function that will retry once and log any error it encounters.
=> Handle DB error

lib/prediction_analyzer/prediction_accuracy/query.ex, test/prediction_analyzer/prediction_accuracy/query_test.exs
No direct ticket, spillover from [Analyzer: Handle occasional database errors](https://app.asana.com/0/584764604969369/1110825829359410/f) and realizing we could do the logging better.
=> Better logging for DB error

assets/brunch-config.js, assets/package-lock.json, assets/package.json, config/config.exs, config/dev.exs, config/test.exs, lib/fake_httpoison.ex, lib/fake_stop_name_fetcher.ex, lib/prediction_analyzer/application.ex, lib/prediction_analyzer/stop_name_fetcher.ex, lib/prediction_analyzer_web/controllers/accuracy_controller.ex, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex, test/prediction_analyzer/stop_name_fetcher_test.exs, test/prediction_analyzer_web/views/accuracy_view_test.exs, test/support/env.ex
**Asana Ticket:** [[5] Analyzer: show stop name](https://app.asana.com/0/584764604969369/1110237990554878)
Changed the input for stop IDs from a text field to a combo box populated with the stop descriptions and stop IDs.
=> Change UI for selecting stop in prediction analyzer

assets/js/chart.js, lib/fake_httpoison.ex, lib/fake_stop_name_fetcher.ex, lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex, lib/prediction_analyzer/stop_name_fetcher.ex, lib/prediction_analyzer_web/controllers/accuracy_controller.ex, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex, test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs, test/prediction_analyzer/stop_name_fetcher_test.exs, test/prediction_analyzer_web/views/accuracy_view_test.exs
**Asana Ticket:** [[5] analyzer: new view comparing stops on a route](https://app.asana.com/0/584764604969369/950496618789686)
A third view is added to the prediction analyzer, where it breaks down accuracy on a stop-by-stop basis.
=> Accuracy-by-stop view

priv/repo/migrations/20190315155432_add_direction_id_to_predictions_and_prediction_accuracy.exs
**Asana Ticket:** [Prediction analyzer filter by direction](https://app.asana.com/0/584764604969369/1002946782363492/f)
This is just the migration adding the `direction_id` column to the appropriate tables.
=> Update schema to add direction ID

assets/js/chart.js, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex, test/prediction_analyzer_web/views/accuracy_view_test.exs
**Asana Ticket:** [Analyzer: Move route selector into filters](https://app.asana.com/0/584764604969369/1115037746846863/f)
Created a new `select` in the form and removed the old buttons. Removed the old JavaScript for handling the route buttons interacting with the form as that's no longer relevant.
=> Move route to a select drop-down

config/config.exs, lib/fake_httpoison.ex, lib/fake_stop_name_fetcher.ex, lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex, lib/prediction_analyzer/predictions/download.ex, lib/prediction_analyzer/stop_name_fetcher.ex, lib/prediction_analyzer/utilities.ex, lib/prediction_analyzer/vehicle_positions/tracker.ex, lib/prediction_analyzer/vehicle_positions/vehicle.ex, lib/prediction_analyzer_web/controllers/accuracy_controller.ex, lib/prediction_analyzer_web/router.ex, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex, lib/utilities/api_v3.ex, priv/repo/seeds.exs, test/prediction_analyzer/predictions/download_test.exs, test/prediction_analyzer/stop_name_fetcher_test.exs, test/prediction_analyzer/vehicle_positions/tracker_test.exs, test/prediction_analyzer_web/controllers/accuracy_controller_test.exs, test/prediction_analyzer_web/views/accuracy_view_test.exs
**Asana Ticket:** [[5] Add Commuter Rail to the prediction accuracy tracker](https://app.asana.com/0/584764604969369/1109400124158019)
download commuter rail data and then analyze it.
=> Pair commuter rail accuracy

assets/css/app.css, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex
**Asana Ticket: no ticket**
We weren't applying the proper style to the button. It also had to be widened a tad to fit the "Commuter Rail" text comfortably.
=> Style the button correctly

assets/css/app.css, assets/js/chart.js, lib/prediction_analyzer_web/templates/accuracy/index.html.eex
**Asana Ticket:** [analyzer - small tweaks to sort button](https://app.asana.com/0/584764604969369/1116467262379014/f)
Updated the text as per the ticket, also figured out what was up with the styling when it was clicked and fixed that.
=> Change the text and styling of the sort button

assets/js/chart.js, lib/prediction_analyzer_web/templates/accuracy/index.html.eex
**Asana Ticket:** [[2] analyzer - add checkbox for "include dev green"](https://app.asana.com/0/584764604969369/1116467262379013)
im not sure im happy with the way i did this, but i think doing it another way might be more annoying, and possibly require page reloads.  Originally i wanted to do a thing where we would just take the dev green data off the page entirely, but that would definitely require a page reload and that is nto what we wanted.
=> checkbox to hide dev green data

lib/prediction_analyzer/prediction_accuracy/accuracy_tracker.ex, test/prediction_analyzer/prediction_accuracy/accuracy_tracker_test.exs
**Asana Ticket:** [[extra - 1] Change PA accuracy alert threshold](https://app.asana.com/0/584764604969369/1121412977008807)
i think 10% is good based on our dashboard on all routes.
=> change threshold to 10%

assets/package-lock.json, assets/package.json
**Asana Ticket:** [[1] Upgrade jQuery to latest version](https://app.asana.com/0/584764604969369/1121557457082959)
I started by updating jQuery to the latest version (3.4.1) but then npm suggested I run `npm audit fix` to fix all vulnerabilities and... well, things got a bit out of hand.
=> update a bunch of stuff with npm audit fix

assets/js/chart.js, config/config.exs, lib/prediction_analyzer/application.ex, lib/prediction_analyzer/filter.ex, lib/prediction_analyzer/prediction_accuracy/accuracy_tracker.ex, lib/prediction_analyzer/prediction_accuracy/aggregator.ex, lib/prediction_analyzer/prediction_accuracy/prediction_accuracy.ex, lib/prediction_analyzer/utilities.ex, lib/prediction_analyzer/weekly_accuracies/aggregator.ex, lib/prediction_analyzer/weekly_accuracies/query.ex, lib/prediction_analyzer/weekly_accuracies/weekly_accuracies.ex, lib/prediction_analyzer_web/controllers/accuracy_controller.ex, lib/prediction_analyzer_web/controllers/predictions_controller.ex, lib/prediction_analyzer_web/templates/accuracy/index.html.eex, lib/prediction_analyzer_web/views/accuracy_view.ex, priv/repo/migrations/20190528184413_add_weekly_accuracies.exs, priv/repo/seeds.exs, test/prediction_analyzer/prediction_accuracy/prediction_accuracy_test.exs, test/prediction_analyzer/utilities_test.exs, test/prediction_analyzer/weekly_accuracies/aggregator_test.exs, test/prediction_analyzer/weekly_accuracies/query_test.exs, test/prediction_analyzer/weekly_accuracies/weekly_accuracies_test.exs, test/prediction_analyzer_web/controllers/accuracy_controller_test.exs
**Asana Ticket:** [[5] Analyzer: Add a "weekly" view](https://app.asana.com/0/584764604969369/1113375993891945)
im putting this up now because i find it easier to see what ive done nwo that im coming back after a long weekend.  feel free to look if youre interested.
=> Weekly view

assets/css/app.css, lib/prediction_analyzer_web/templates/accuracy/index.html.eex
**Asana Ticket:** [📈 Add explanation for prediction-accuracy metric calculation](https://app.asana.com/0/584764604969369/1118056447625835)
heres an attempt at css toggling that seems ok to me.  open to doing it differently though.
=> toggle buttons for reminder text

lib/prediction_analyzer/pruner.ex
**Asana Ticket:** [💳 Prediction analyzer pruning failing](https://app.asana.com/0/584764604969369/1130638623059531)
the time seems to have been put a little far in the future.
=> schedule pruning for 12 hours, not 500 days

lib/prediction_analyzer/vehicle_positions/comparator.ex, test/prediction_analyzer/vehicle_positions/comparator_test.exs
**Asana Ticket:** [🐛multiple updates error ](https://app.asana.com/0/584764604969369/1138809250698897)
make it an info if its cr
=> log an info if we get multiple departues on the cr instead of a warning

lib/prediction_analyzer/pruner.ex, test/prediction_analyzer/pruner_test.exs
**Asana Ticket:** [🐛 [extra] Prediction Analyzer is failing to prune again](https://app.asana.com/0/584764604969369/1138209323013289/f)
Per discussion on Slack, we're failing to prune because we're trying to delete vehicle events that still have associated predictions. When taking a given vehicle event and associating a predictions with it, we look back at predictions from the last half hour, at most, so if we shift the time cutoff for deleting a vehicle event forward 30 minutes relative to that for predictions, it shouldn't hit any conflicts.
=> Shift pruning cutoff for vehicle_events forward 30 minutes

lib/prediction_analyzer/vehicle_positions/tracker.ex, test/prediction_analyzer/prediction_accuracy/aggregator_test.exs, test/prediction_analyzer/vehicle_positions/tracker_test.exs
**Asana Ticket:** [📈🔍 "Subway vehicle positions not modified since last request" warnings](https://app.asana.com/0/584764604969369/1126521085025069/f)
It looks like we can just reduce the severity, see my notes in the ticket on the investigation.
=> Make warnings about vehicle positions not modified into info

assets/package-lock.json
**Asana Ticket:** none
Just did `npm update` from our `assets` directory.
=> chore: Update JS deps

lib/prediction_analyzer_web/controllers/accuracy_controller.ex, test/prediction_analyzer_web/controllers/accuracy_controller_test.exs
**Asana Ticket:** [📈🐛 Correct ordering of entries in PA daily accuracy view](https://app.asana.com/0/584764604969369/1144268954474545/f)
Sort the dates as dates!
=> fix: make dates appear in correct order in table

.tool-versions, Dockerfile, semaphore/setup.sh
Update Elixir 1.9.1 -> 1.10.2 and Erlang 22.1.7 -> 22.3.3.
=> chore: Update elixir to 1.10.3 and erlang to 22.3.3

priv/repo/migrations/20201027201115_add_kind_to_predictions.exs, priv/repo/structure.sql
**Asana Ticket:** [📈 tracking kind of prediction and being able to filter](https://app.asana.com/0/584764604969369/1187025758962797)
=> chore: add migration for prediction kind

priv/repo/migrations/20201103215547_nth_at_stop_cols.exs, priv/repo/structure.sql
**Asana Ticket:** [Schema changes](https://app.asana.com/0/584764604969369/1196327338606455)
=> chore: Update schema for nth_at_stop feature

semaphore/build_push.sh
Log in to docker with the ENV var in semaphore if available.
=> chore: Login to docker when building image

.dockerignore, .github/workflows/deploy-dev.yml, .github/workflows/docker.yml, .github/workflows/report-coverage.yml, .tool-versions, Dockerfile
**Asana Ticket:** [fix prediction_analyzer deploys](https://app.asana.com/0/881264583703207/1200307100425040)
=> ci: update to Node 14, multi-stage Docker build

.github/workflows/deploy-ecs.yml
just a stub since the workflow needs to be merged in the first place, in order for me to iterate on it and test it in a branch.
=> chore: GitHub Action deploy ECS stub

.github/workflows/deploy-ecs.yml
Looks like we just have to provide a default value here.
=> fix: Deploys when merging PR

.tool-versions, Dockerfile, lib/prediction_analyzer/utilities.ex
**Asana Ticket:** [Update RTR to handle Union Sq trains](https://app.asana.com/0/584764604969369/1201366718768696/f)
Added generic_stop_id matching for Union Square, updated Elixir and Erlang versions to latest patch.
=> Add matching for Union Square

.github/workflows/ci.yml, .github/workflows/deploy-ecs.yml
**Asana Ticket:** [Setup GitHub Actions for nightly CI + dev deploy runs](https://app.asana.com/0/584764604969369/1203566390446223/f)
This adds a build and dev deploy workflow run every day at midnight.
=> ci: added scheduled builds

Dockerfile
This PR adds a few native libraries missing from the base image that the VM produced errors about missing after upgrading.
=> fix: added missing system packages

.github/workflows/asana.yml
**Asana Ticket:** [[extra] fix Asana workflow in Prediction Analyzer](https://app.asana.com/0/584764604969369/1205953777846448/f)
Switches to the shared version of the Asana workflow. This should fix the problems with Dependabot and Asana.
=> ci: fix asana workflow for dependabot

.github/workflows/ci.yml, lib/prediction_analyzer/repo.ex
**Asana Ticket:** -
Fixes a mistake I made in #785.
=> Fix a mistake, bump upload-artifact version in CI

lib/prediction_analyzer/prediction_accuracy/accuracy_tracker.ex, test/prediction_analyzer/prediction_accuracy/accuracy_tracker_test.exs
**Asana Ticket:** [📈🐛 Prediction Analyzer accuracy_drop not working as expected](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210631075989250?focus=true)
[Please include a brief description of what was changed]
=> fix: accuracy drop is not calculated seperately across routes

priv/repo/migrations/20250708201320_add_dev_blue_environment.exs, priv/repo/structure.sql
**Asana Ticket:** NO TICKET
[Please include a brief description of what was changed]
=> fix: add dev-blue to environment enum
